name: Build EngenhariaSonora Loader

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          target: aarch64-linux-android
      - name: Build with Cargo
        run: |
          cargo build --release --target aarch64-linux-android
      - name: Upload Binary
        uses: actions/upload-artifact@v4
        with:
          name: mtbinloader2-optimized
          path: target/aarch64-linux-android/release/libmtbinloader2.so
